version: "3.8"
services:
  nginx:
    container_name: nginx
    build:
      context: ./nginx/.
      dockerfile: Dockerfile
    ports:
      - 8000:80
    depends_on:
      - backend
      - frontend
    restart: always

  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./backend/:/backend/
    environment:
      - WAIT_HOSTS=frontend:80
    depends_on:
      - frontend
      - db

  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - ./frontend/:/frontend/
      - ./frontend/dist:/frontend/dist
      - ./frontend/node_modules:/frontend/node_modules

  db:
    container_name: db-mysql
    image: mysql:8.0
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_HOST: root
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: turtle-neck-savior-dev
    volumes:
      - ./mysql:/var/lib/mysql
    command:
      - "--character-set-server=utf8mb4"
      - "--collation-server=utf8mb4_unicode_ci"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10
